### ISSUE TITLE
言語ごとのフォルダ用意

### ISSUE THREAD

**Issue by chinchillaa** [tky1645/TIL#1]

**Comment by tky1645** [comment]
空のフォルダをコミットできねえ。。。

**Comment by chinchillaa** [comment]
コメント気づいてなかったw
空のフォルダ内に.gitkeepってファイル置くとコミットできるっすよ！
https://qiita.com/ndxbn/items/f124d2b183b60cb074e2

**Comment by tky1645** [comment]
知らんかったサンクス！
